### PR TITLE
Db init config

### PR DESCRIPTION
**Pull request by Adobe-Android**
Added the initial work I've done for configuration management. I still need to round out the config file generation and test it out before this functionality is complete. Also made a couple changes to the gitignore file to avoid extra annoying IDE specific folders.

Instructions:
To run the associated project, open the project folder and run the following command from the terminal.
The project will automatically restore its dependencies.

```dotnet run```

If you don't already have .NET Core
https://www.microsoft.com/net/download

### CODE REVIEW

**Comment by glenvollmer** [comment]
could you include instructions on how to run what you've got so far and if there are any other prerequisites for running your code?

**Comment by glenvollmer** [comment]
so the build should succeed, and then when I run everything it should just hang and display a message that says "Type the full file path to the file you want to play" ??? If that is what I am supposed to get then its cool by me to go ahead and merge

**Comment by glenvollmer** [comment]
I am also a little confused about the `mp3Path` that you are declaring in the Program.cs file.
would you mind explaining what that is for? because you are adding '/sample.mp3' to the end of a path to a json file, which I do not believe will be a valid file path.

**Comment by glenvollmer** [comment]
Also, I saw that you started on some other files, which is awesome!!! but I also noticed that they fall under other tickets that are still in todo. We should probably break those issues out into more detail so we can more accurately track the progress.

**Comment by Adobe-Android** [comment]
Yes, all your assumptions are correct. I only touched the other files to give everyone a good starting point and to help avoid issues that could come up if a file didn't live in the same namespace as everything else. A common pitfall for a beginning C# developer.

**Pull request merged**
